#---APPLICATION SETINGS---------------------------------------------------------
flowSolver                        = false
gridGenerator                     = true

#---APPLICATION ENVIRONMENT-----------------------------------------------------
outputDir                         = "out_lb/"
geometryInputFileName             = "geometry.toml"
gridOutputFileName                = "grid.Netcdf"

#---NUMERICAL PROPERTIES--------------------------------------------------------
nDim                              = 3
noSolvers                         = 2
multiSolverGrid                   = true

#---GRID PROPERTIES-------------------------------------------------------------
scratchSize                       = 20.0
maxNoCells                        = 100000000    # maximum number of cells per process

reductionFactor                   = 1.0  #0.01      # factor by which level-0 cell length is multiplied
noHaloLayers                      = 2
partitionCellOffspringThreshold   = 500000

minLevel                          =  8        # refine the grid to minLevel serial
maxUniformRefinementLevel         =  9        # refine parallelto maxUniformRefinementLevel
maxBoundaryRfnLvl                 =  12        # Boundary refinement to maxBoundaryRfnLevel
maxRfnmntLvl                      =  12        # Local refinements to maxRfnmntLvl

localRfnMethod                    = 1 #3         # 0 no, 1 patch only, 2 boundary only, 3 both

#-boundary refinment
#localBndRfnMethod                 = 2         # 0: default (level0), 1: based on local 2: based on localBndRfnDistance
#localBndRfnDistance               = 0.5       # d_bndry/D= 5/sqrt(Re)
#localBndRfnMinLvlDiff             = [3]       # difference between maxBoundaryRfnLvl and lowest target refinment level

localRfnBoundaryIds               = [6,7,8]       # Ids of boundaries that are refined
#localRfnLvlDiff                   = [0]       # difference between maxBoundaryRfnLvl and bndry-Id
smoothDistance                    = 3      # number of cells used at least
localMinBoundaryThreshold         = 3      # 

localRfnLvlMethods              = "B-B-CCC-CCC-CCC"
localRfnLevelProperties         = [
  -3.5, -2.5, -3.0,  6.0, 2.5, 3.0,
  -2.5, -2.0, -3.0,  5.0, 2.0, 3.0,
  -1.299, 0.0, -3.0, -1.299, 0.0, 3.0, 0.640,
  0.0, 0.75, -3.0, 0.0, 0.75, 3.0, 0.640,
  0.0, -0.75, -3.0, 0.0, -0.75, 3.0, 0.640,
  -1.299, 0.0, -3.0, -1.299, 0.0, 3.0, 0.560,
  0.0, 0.75, -3.0, 0.0, 0.75, 3.0, 0.560,
  0.0, -0.75, -3.0, 0.0, -0.75, 3.0, 0.560,
  -1.299, 0.0, -3.0, -1.299, 0.0, 3.0, 0.520,
  0.0, 0.75, -3.0, 0.0, 0.75, 3.0, 0.520,
  0.0, -0.75, -3.0, 0.0, -0.75, 3.0, 0.520,
]

#cutOff            = 1
#cutOffMethod      = "B"
#cutOffCoordinates = [-1000.0,-1000.0,-1.0, 1000.0,1000.0,1.0]
