noSegments       = 7
inOutSegmentsIds = [0,1,2,3]

filename.0 = "stl/negX.stl"
filename.1 = "stl/posX.stl"
filename.2 = "stl/negY.stl"
filename.3 = "stl/posY.stl"
filename.4 = "stl/cylinder_front.stl"
filename.5 = "stl/cylinder_up.stl"
filename.6 = "stl/cylinder_down.stl"

"body_segments.boundary" = [0,1,2,3,4,5,6]

BC.0 = 1000
BC.1 = 4000
BC.2 = 4000
BC.3 = 4000
BC.4 = 2008
BC.5 = 2008
BC.6 = 2008