noSegments = 10
inOutSegmentsIds = [0, 1, 2, 9]

filename.0 = "stl/edge.0"
filename.1 = "stl/edge.1"
filename.2 = "stl/edge.2"
filename.3 = "stl/edge.3"
filename.4 = "stl/edge.4"
filename.5 = "stl/edge.5"
filename.6 = "stl/edge.6"
filename.7 = "stl/edge.7"
filename.8 = "stl/edge.8"
filename.9 = "stl/edge.9"

"body_segments.boundary" = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

BC.0 = 1000
BC.1 = 3020
BC.2 = 4000
BC.3 = 2000
BC.4 = 2000
BC.5 = 2000
BC.6 = 2000
BC.7 = 2000
BC.8 = 2007
BC.9 = 4000